### ISSUE TITLE
Router does not handle HTTP Methods

### ISSUE THREAD

**Issue by celliott181** [jquave/tasty#11]
Adding this here to track changes needed to start handling the various HTTP methods. Currently any method will be handled by the passed handler, meaning it's up to the end user to understand and implement the various methods instead of allowing smaller handlers per-method.

I have some preliminary work in my fork that modifies the `Router.on()` api. Proposed change will use `Router.on(config: RouteConfig, handler: Handler)` as the API.

RouteConfig will look roughly like this:
```
{
  method: string,
  path: string
}
```

I'll probably also add a type for the method that limits entry to the standard HTTP method names, but for now this should let us add per-method actions, like POSTing to `/route` performing one action while GETing `/route` will perform another.

Also considering updating `Handler` to `RouteHandler` to get a little more clarity on what exactly it handles.

**Comment by jquave** [comment]
I was thinking perhaps the `Router.on` method would be a general-purpose handler config, while we would also offer `Router.get`, `Router.post`, `Router.put`, `Router.patch`, and `Router.delete`, in order to simplify the code at the call-site

**Comment by celliott181** [comment]
For individual `get()`, `post()`, `put()` methods we could do a private `on()` implementation handling the actual route config as above, then expose the specific methods as public API to get the simplified call site benefits.

The reasoning I had for a single `on()` function is to make the move to a map-based router table. Each method would have its route list stored against the method as a key. Long term I think it'd be great to have a route tree to improve lookup, but for now an array based lookup as is won't hinder things. 

I'll round out the implementation for you to check out this evening and see if it matches your api goals and gets some cleaner internals.

**Comment by jquave** [comment]
We could do both, provide the individual methods and also have it backed by a map-based implementation. I can't think of a good reason to specifically include `on` as a public-facing API. It would only be in the name of flexibility to keep it, but my goal with this framework is simplicity, not flexibility.

**Comment by celliott181** [comment]
In this case `on()` would reduce code duplication around pulling the route table and inserting a route. As I mentioned, it would be a private internal function that is called by the public method-specific calls. Clean public API, smaller footprint on the inside.

I was going with the public `on()` as that's the current API. I'm all for easier to use.

**Comment by jquave** [comment]
Yep, let's do it this way, also glad to have you contributing to the project! I created a gitter for this project for easier back and forth discussion: https://gitter.im/tasty-dev/community

**Comment by celliott181** [comment]
Closed with #12 and #13
